logging:
  level:
        com:
          example:
            JournalEntry: OFF

food:
  api:
    base-url: "https://www.themealdb.com/api/json/v1/1/search.php?s=FOOD_iTEM"


spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: chandun3co@gmail.com
    password: bigm pehy crlm aqxa
    properties:
          mail:
            smtp:
              auth: true
              ssl:
                enable: true
                trust: smtp.gmail.com
                protocols: TLSv1.2



