spring.mongodb.uri=mongodb+srv://chanduuser:Ohw54SmkmWYGEEG5@cluster0.exfr9is.mongodb.net/journaldb?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true
server.port=8081
logging.level.org.springframework.security=DEBUG